2018-06-21 10:46:55,153 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:07:56,994 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:10:53,906 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:24:51,427 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:24:57,913 ERROR: Exception on /predictmany [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-06-21 13:25:27,344 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:27:21,454 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:31:01,823 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:31:40,757 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:41:55,224 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:41:58,400 ERROR: Exception on /predictmany [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/restapi/routes.py", line 31, in predictmany
    print(sentiment_dict[pred])
KeyError: 1
2018-06-21 13:42:22,961 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:48:02,673 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:48:05,147 ERROR: Exception on /predictmany [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/restapi/routes.py", line 32, in predictmany
    prediction_labels.append[sentiment_dict[pred]]
TypeError: 'builtin_function_or_method' object is not subscriptable
2018-06-21 13:48:25,386 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:50:29,662 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:54:09,108 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:54:49,993 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:55:35,316 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:56:46,060 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 13:59:18,589 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:01:35,709 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:02:04,552 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:02:45,526 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:03:06,664 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:09:55,418 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:10:28,451 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:27:18,044 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
2018-06-21 14:27:23,767 ERROR: Exception on /predictmany [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/restapi/routes.py", line 16, in predictmany
    predictions,prediction_labels=model.get_predicttions(test_df['comment'])
AttributeError: 'Mlmodel' object has no attribute 'get_predicttions'
2018-06-21 14:30:04,180 INFO: ML RESTAPI startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/sentimentpredictor/webapp/__init__.py:38]
